FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

COPY ./dist ./dist

CMD ["npm", "run", "start:dev"]


#FROM node:18-alpine
#
#WORKDIR /app
#
#RUN git clone
#
#COPY package*.json ./
#
#COPY . .
#
#RUN npm install
#
##RUN npm run build
#
##COPY ./dist ./dist
#
#CMD ["npm", "run", "start:loсal:dev"]
